language: java
jdk:
  - openjdk8
  - openjdk11

install: skip
script: cd log4jSyslogWriter64k && mvn install -Dgpg.skip=true --batch-mode --show-version --update-snapshots

cache:
  directories:
    - $HOME/.m2/repository
